#1 Start
KrasnyiM/Orion pull request #1
Opened 2024-09-04 19:43 UTC by KrasnyiM

2024-09-05 08:37 UTC, ryzhkovAndruha commented on OrionWebAPI.sln
Shouldn't this file be under gitignore?

2024-09-05 08:37 UTC, ryzhkovAndruha commented on DbGame/User.cs
> +using System.Threading.Tasks;
Remove unnecessary usings

2024-09-05 08:37 UTC, ryzhkovAndruha commented on DbGame/GameDto.cs
> +using System.Threading.Tasks;
Remove unnecessary usings

2024-09-05 08:38 UTC, ryzhkovAndruha commented on DbGame/UserRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary usings

2024-09-05 08:38 UTC, ryzhkovAndruha commented on OrionWebAPI/AutoMapperProfile.cs
> +using AutoMapper;
Remove unnecessary usings

2024-09-05 08:38 UTC, ryzhkovAndruha commented on DbGame/Accounting.cs
> +using System.Threading.Tasks;
Remove unnecessary usings

2024-09-05 08:38 UTC, ryzhkovAndruha commented on DbGame/ApplicationContext.cs
> +using Microsoft.Extensions.Options;
Remove unnecessary usings

2024-09-05 08:39 UTC, ryzhkovAndruha commented on DbGame/ApplicationContext.cs
> +            //        });
Good practice is when you don't have commented code. Either delete it or uncomment it

2024-09-05 08:39 UTC, ryzhkovAndruha commented on DbGame/DbGame.csproj
Shouldn't this file be under gitignore?

2024-09-05 08:40 UTC, ryzhkovAndruha commented on OrionWebAPI/OrionWebAPI.csproj
Shouldn't this file be under gitignore?

2024-09-05 08:40 UTC, ryzhkovAndruha commented on OrionWebAPI/Program.cs
> +//builder.Services.AddScoped<ApplicationContext>();
Why this code is commented?

2024-09-05 08:41 UTC, ryzhkovAndruha commented on OrionWebAPI/appsettings.json
> +  },
This is very sensetive information, that should not be pushed to your github. Read about user secrets

2024-09-05 08:42 UTC, ryzhkovAndruha requested changes
Read the comments that should be changed

2024-09-06 18:57 UTC, KrasnyiM commented on OrionWebAPI/Program.cs
> +//builder.Services.AddScoped<ApplicationContext>();
I forgot to delete this code line. I practice different ways to inject objects, and then I understand to work without explicit implementation. If I understand all right.

2024-09-08 18:23 UTC, ryzhkovAndruha approved these changes

2024-09-10 17:20 UTC, merged